// STATUS
const USER_STATUS_ACTIVE = 'active';
const USER_STATUS_INACTIVE = 'inactive';
const USER_STATUS_LIST = [USER_STATUS_ACTIVE, USER_STATUS_INACTIVE];

// ROLES
const USER_ROLE_ADMIN = 'admin';
const USER_ROLE_USER = 'user';
const USER_ROLE_LIST = [USER_ROLE_ADMIN, USER_ROLE_USER];

module.exports = {
  USER_STATUS_ACTIVE,
  USER_STATUS_INACTIVE,
  USER_STATUS_LIST,
  USER_ROLE_ADMIN,
  USER_ROLE_USER,
  USER_ROLE_LIST,
};
